# Generated by Django 5.1.6 on 2025-02-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(default='avatar.jpg', upload_to='Profile_Images'),
        ),
    ]
