# Generated by Django 5.1.6 on 2025-02-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Comp Electricos', 'Comp Electricos'), ('Computadores', 'Computadores'), ('Televisores', 'Televisores')], max_length=20, null=True),
        ),
    ]
